### PR TITLE
Pass a managed instance for save instead of the detached one

### LINKED ISSUE #147: Detached messages are duplicated by the MessageManager
-<b>Description</b>

If MessageManager::save() encounters a detached <code>$message</code> it tries to merge it:

<code>$this->getEntityManager()->getUnitOfWork()->merge($message);</code>

This code returns a <b>new</b> managed instance, but it is not assigned to <code>$message</code>.

Thus the old, unmanaged version of the message is passed down and persisted when calling:
<code>parent::save($message, $andFlush)</code>

This results in a duplicate entry of the message.

-<b>Steps to reproduce</b>

To reproduce this I set up the bundle with doctrine (using the default connection and entity manger). 
With this setup calling <code>$em->clear()</code> during ConsumerInterface::process() results in a duplicate message (in DB) for each processed message

-<b>Proposed solution</b>

I reckon this should do the trick:

<code>$message = $this->getEntityManager()->getUnitOfWork()->merge($message);</code>

### PR DESCRIPTION
**Pull request by excursions**
Fixes #147

### CODE REVIEW

**Comment by greg0ire** [comment]
"manged"? Are you french and do you mean "eaten" ;) ?

**Comment by excursions** [comment]
@greg0ire Cheers :)

**Comment by greg0ire** [comment]
Can you explain why you are doing this in the commit body ?

e.g. : 

> pass a manged instance for save instead of the detached one 
>
> Passing a managed instance implies a new entity, which is bad because… what?

**Comment by excursions** [comment]
Ping @greg0ire

**Comment by greg0ire** [comment]
Excellent :+1:

**Comment by core23** [comment]
Thank you @excursions

**Pull request merged**
