### PR TITLE
Allow Support PHP 8.0

### PR DESCRIPTION
**Pull request by Yozhef**
## Changelog

```markdown
### Added
- Add support for PHP 8.0
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
A release is needed for sonata-project/datagrid-bundle

**Comment by VincentLanglet** [comment]
Blocker by sonata-project/doctrine-orm-admin-bundle now

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
We need the dev kit PR @Yozhef

**Comment by Yozhef** [comment]
@jordisala1991 yes, 5 min =)

**Comment by Yozhef** [comment]
@jordisala1991 https://github.com/sonata-project/dev-kit/pull/1429

**Comment by wbloszyk** [comment]
@sonata-project/contributors @Yozhef 
We have problem here. Some dependencies are not allowed for php 8.0.

```
composer why-not php 8.0
php-amqplib/php-amqplib  2.12.2  requires  php (>=5.6.3,<8.0)  
```

**Comment by VincentLanglet** [comment]
This is not a dependency https://github.com/sonata-project/SonataNotificationBundle/blob/3.x/composer.json#L23

**Comment by Yozhef** [comment]
@wbloszyk php-amqplib/php-amqplib in master support - ned wait release =(

**Comment by wbloszyk** [comment]
> @wbloszyk php-amqplib/php-amqplib in master support - ned wait release =(

My bad, `"php": ">=7.0",`.

**Comment by Yozhef** [comment]
@wbloszyk ви праві зараз остання версія https://packagist.org/packages/php-amqplib/php-amqplib#2.12.2 не підтримує PHP 8.0 = (php:> = 5.6.3, <8.0 =(

**Pull request merged**
