### PR TITLE
Make REST dependency optional

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @rande

**Comment by OskarStark** [comment]
Refs sonata-project/SonataPageBundle#577

**Comment by OskarStark** [comment]
Refs sonata-project/SonataNewsBundle#282

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataUserBundle/pull/650

**Comment by core23** [comment]
@rande Can you have a look if we could remove the REST API dependencies for the ref'd bundles?

**Comment by core23** [comment]
@OskarStark Can you have a look at these and the ref'd tickets please?

**Comment by OskarStark** [comment]
Thank you @core23

**Pull request merged**
