### PR TITLE
Make services public

### PR DESCRIPTION
**Pull request by core23**
I am targeting this branch, because this is a bugfix.

## Changelog

```markdown
### Changed
 - Make services public
```

### CODE REVIEW

**Comment by OskarStark** [comment]
@covex-nn please don't forget to add the corresponding labels.

@greg0ire @core23 , `Changed` is used in the chagelog, but IMO its a `patch` not a `minor`.
Could we use `Changed` anyway or do we need to change it to `Fixed`?

**Comment by core23** [comment]
Changed the `Changed` to a `Fixed`

**Comment by OskarStark** [comment]
Thank you @core23 , can you handle the other PR's too?

**Comment by core23** [comment]
It's already done

**Pull request merged**
