### PR TITLE
Drop SonataCoreBundle

### LINKED ISSUE #423: SonataCoreBundle is deprecated
As stated on [its README](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/README.md), SonataCoreBundle is deprecated.

This bundle should not rely on SonataCoreBundle anymore

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

I am targeting this branch, because it its BC-break.

Closes #423 

## Changelog

```markdown
### Removed
- Removed `SonataCoreBundle` 
```

### CODE REVIEW

**Comment by wbloszyk** [comment]
@greg0ire SerializerBundle must be upgrade to 3 with form-extensions. Can u check travis? It look good but for `--prefer-lowest` test is timeout.

**Comment by greg0ire** [comment]
No link to Travis… I'm going to try to apply this first: https://twitter.com/alex_s_/status/1244288769886478341

**Comment by greg0ire** [comment]
I think I lack some permissions to do the migration, I asked somebody who doesn't

Also, I can't find the build… let's try close and reopen.

**Comment by greg0ire** [comment]
Thanks @wbloszyk !

**Pull request merged**
