### PR TITLE
All symfony/symfony package is not needed

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@rande Then I think I had to pick only needed packages too? :-)

**Comment by rande** [comment]
@Soullivaneuh yep, all Sonata's bundles do not get the same love :/

**Comment by Soullivaneuh** [comment]
Well, big `symfony/symfony` package was required for this one. I think it's *a little bit* too much. :-P

**Comment by Soullivaneuh** [comment]
Well, `framework-bundle` is required for commands.

**Pull request merged**
