### PR TITLE
Updated some german translations

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
This is not really a correction, another translations as the same `Id` notation.

See here: https://github.com/sonata-project/SonataNotificationBundle/blob/master/Resources/translations/SonataNotificationBundle.en.xliff#L17-L20

Regards.

**Comment by OskarStark** [comment]
In the Otter Sonata bundles they use it like this

**Comment by OskarStark** [comment]
Other *

**Comment by Soullivaneuh** [comment]
@OskarStark on which ones?

**Pull request closed without merging**
