### PR TITLE
error levels should be integer instead of scalar

### PR DESCRIPTION
**Pull request by OskarStark**
Defined here:
https://github.com/sonata-project/SonataNotificationBundle/blob/master/Resources/config/doctrine/BaseMessage.orm.xml#L6

@rande can you verify this?

### CODE REVIEW

**Comment by OskarStark** [comment]
could you please verify this @rande ??

**Comment by Soullivaneuh** [comment]
> could you please verify this @rande ??

He will when it will got some time @OskarStark, don't ping multiple times a day.

For me it looks fair enough.

**Comment by OskarStark** [comment]
:+1:

**Comment by OskarStark** [comment]
PR rebased

**Comment by OskarStark** [comment]
ping @rande

**Comment by OskarStark** [comment]
I verified this, it is compared here:
https://github.com/sonata-project/SonataNotificationBundle/blob/master/DependencyInjection/SonataNotificationExtension.php#L176

**Pull request merged**
