### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by gremo**
Add italian translation

### CODE REVIEW

**Comment by gremo** [comment]
Can you please merge this so I can clean up my forked repositories? Thanks

**Comment by greg0ire** [comment]
We literally can't click the button if the styleci test does not pass… not you're problem though, I'll notify the relevant people.

**Comment by greg0ire** [comment]
Hey @gremo! I got StyleCI to fix this, can you amend and force push? That will re-trigger the build.

**Comment by greg0ire** [comment]
Nevermind, closing and reopening works.

**Comment by greg0ire** [comment]
Thanks @gremo !

**Pull request merged**
