### PR TITLE
3.12.0

### PR DESCRIPTION
**Pull request by phansys**

### CODE REVIEW

**Review by VincentLanglet — DISMISSED** [review]

**Comment by phansys** [comment]
We have a problem between "nelmio/api-doc-bundle:2.x" and "symfony/config:5.x".
This issue was not detected by the tests in this package, but it is exposed by sonata-project/SonataMediaBundle#1930.

**Comment by wbloszyk** [comment]
IMO I have to finish https://github.com/sonata-project/dev-kit/issues/778

**Comment by phansys** [comment]
> IMO I have to finish [sonata-project/dev-kit#778](https://github.com/sonata-project/dev-kit/issues/778)

I agree, but in case we want to support "symfony/config:5.x" we MUST drop support for "nelmio/api-doc-bundle:2.x", unless this package make the [required backport](https://github.com/nelmio/NelmioApiDocBundle/pull/1457#issuecomment-796620190) for the FC layer in the unmaintained `2.x` branch.

**Comment by wbloszyk** [comment]
As we can not add support for Symfony5 in sonata 3 we should revert this:
- [[#564](https://github.com/sonata-project/SonataNotificationBundle/pull/564)] Support for "symfony/config:^5.2" ([@phansys](https://github.com/phansys))

In sonata 4 we should move REST API to seperate bundle and problem with symfony/config 5.x will be resolved. More info about move REST API you can find here: https://github.com/sonata-project/dev-kit/issues/1465

**Comment by phansys** [comment]
Have this package other issues than the one related to "nelmio/api-doc-bundle:2.x"?
I'm fine if we must remove the support for that version.

**Comment by wbloszyk** [comment]
> Has this package other issues than the one related to "nelmio/api-doc-bundle:2.x"?
> I'm fine if we must remove the support for that version.

For now we know only about "nelmio/api-doc-bundle:2.x"

**Comment by phansys** [comment]
>For now we know only about "nelmio/api-doc-bundle:2.x"

See nelmio/NelmioApiDocBundle#1799.

**Comment by jordisala1991** [comment]
Since the issue with nelmio is solved maybe we can release this now?

**Review by wbloszyk — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Pull request merged**
